### ISSUE TITLE
size of the map window does not fit on the screen

### ISSUE THREAD

**Issue by mercury131** [kzvdar42/jackal#2]
Hello! Your game is amazing! But, when the  1920 * 1080 resolution is used, the size of the map window does not fit on the screen. Can you suggest how to fix this?
I am using resolution 1920 * 1080 (16:9)

**Comment by mercury131** [comment]
I change  tile_size to 70 in https://github.com/kzvdar42/jackal/blob/master/App.py .
Now Its show map correctly.

**Comment by kzvdar42** [comment]
Wow, haven't thought that someone could find this project and find it interesting😅

Yeah, I've never polished the game to work on different devices and just ajusted it for my monitor.

Thanks for leaving the issue, maybe this will give me a push to finish the game)

(There is still one bug in game logic and no screens before/after the game)
